FROM fedora:latest

RUN yum -y groups install "Development Tools"
RUN yum -y install cmake
RUN yum -y install gcc-c++

RUN mkdir /home/work
RUN cd /home/work && git clone https://github.com/qiicr/dcmqi.git && mkdir dcmqi-build
RUN cd /home/work/dcmqi-build && cmake ../dcmqi && make

ENTRYPOINT ["/bin/csh"]


