FROM thewtex/centos-build

MAINTAINER fedorov

WORKDIR /usr/src
RUN git clone https://github.com/QIICR/dcmqi.git && \
  cd dcmqi/docker && \
  make docker.generate_package

WORKDIR /usr/src/dcmqi/docker
ENTRYPOINT ["/bin/bash"]
